In [1]:
import numpy as np

In [2]:
n2 = np.ones(30)

In [4]:
n3 = n2

In [5]:
n3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
n3[ : ] = 100

In [7]:
n3

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

In [9]:
array1 = np.arange(21,32)

In [10]:
array2 = np.arange(11,22)

In [11]:
array1 - array2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [31]:
a1 = np.arange(2,11,2)
a2 = np.arange(22,31,2)
np.vstack((a1,a2))

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

In [32]:
np.column_stack((a1,a2))

array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

In [46]:
a3 = np.arange(30)

In [49]:
a3.shape = [5,6]
a3


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [51]:
a3[1,2]

8

In [54]:
ide = np.ones(100).reshape(10,10)

In [56]:
ide[ : ] = 21

In [57]:
ide

array([[21., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21., 21.]])

In [61]:
arr = np.eye(10)
arr[arr == 0] = 21
arr

array([[ 1., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21.,  1., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21.,  1., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21.,  1., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21.,  1., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.,  1., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21.,  1., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21.,  1., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21.,  1., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.,  1.]])

In [68]:
ar = np.random.rand(10)
ar>0.2

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [73]:
np.random.randn(5,2)

array([[-0.09870239,  1.96990357],
       [-0.1273023 , -0.17764765],
       [-0.27696896, -2.47104021],
       [ 0.04562416,  0.32175913],
       [ 0.19232962, -0.01970624]])

In [77]:
np.linspace(0,100,30)

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [80]:
simple_matrix = np.arange(1,101).reshape(10,10)
simple_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [82]:
simple_matrix[ :8,0:3]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43],
       [51, 52, 53],
       [61, 62, 63],
       [71, 72, 73]])

In [85]:
simple_matrix[5,4]

55

In [89]:
simple_matrix[ : ,2]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [92]:
simple_matrix[3,:]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [94]:
simple_matrix[(1,3),:]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [95]:
simple_matrix.sum()

5050

In [96]:
simple_matrix.std()

28.86607004772212

In [97]:
simple_matrix.mean()

50.5

In [98]:
simple_matrix.max()

100

In [99]:
simple_matrix.min()

1